# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at_time',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name': 'Детали заказа', 'verbose_name_plural': 'Детали заказа'},
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='meal',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время доставки'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.ComplexDinner', verbose_name='Входит в состав обеда'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
